/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Document {
  'status' : DocumentStatus,
  'blobKey' : [] | [ExternalBlob],
  'phase' : DocumentPhase,
  'docType' : string,
  'candidateId' : bigint,
}
export type DocumentPhase = { 'PreOffer' : null } |
  { 'PostOffer' : null } |
  { 'PreJoining' : null };
export type DocumentStatus = { 'Uploaded' : null } |
  { 'Verified' : null } |
  { 'Pending' : null };
export type ExternalBlob = Uint8Array;
export interface Indent {
  'id' : bigint,
  'status' : IndentStatus,
  'jobDescription' : string,
  'role' : string,
  'experienceRange' : string,
  'approver' : [] | [string],
  'createdTimestamp' : Time,
  'department' : string,
  'requiredSkills' : Array<string>,
  'positions' : bigint,
}
export type IndentStatus = { 'BusinessHeadPending' : null } |
  { 'DirectorPending' : null } |
  { 'Approved' : null } |
  { 'Draft' : null } |
  { 'Rejected' : null };
export type InductionStatus = { 'Scheduled' : null } |
  { 'Completed' : null };
export type InterviewStatus = { 'Scheduled' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null };
export type OfferStage = { 'Sent' : null } |
  { 'Draft' : null } |
  { 'Rejected' : null } |
  { 'Accepted' : null } |
  { 'Negotiating' : null };
export type OnboardingStatus = { 'InProgress' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export type ScreeningResult = { 'OnHold' : null } |
  { 'Rejected' : null } |
  { 'Shortlisted' : null };
export type Source = { 'Website' : null } |
  { 'Manual' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : [] | [string],
  'department' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAIInterview' : ActorMethod<
    [bigint, Time, boolean, bigint, string],
    undefined
  >,
  'addDocument' : ActorMethod<
    [bigint, DocumentPhase, string, DocumentStatus, [] | [ExternalBlob]],
    undefined
  >,
  'addInduction' : ActorMethod<
    [bigint, Time, Array<string>, InductionStatus, string],
    undefined
  >,
  'addInterviewRound' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      Time,
      InterviewStatus,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      string,
    ],
    undefined
  >,
  'addOffer' : ActorMethod<[bigint, string, Time, OfferStage], undefined>,
  'addOnboardingDay' : ActorMethod<
    [bigint, bigint, string, OnboardingStatus, string, string],
    undefined
  >,
  'addScreening' : ActorMethod<[bigint, ScreeningResult, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCandidate' : ActorMethod<
    [string, string, string, bigint, Array<string>, string, Source, bigint],
    bigint
  >,
  'createIndent' : ActorMethod<
    [string, string, bigint, string, Array<string>, string],
    bigint
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidateDocuments' : ActorMethod<[bigint], Array<Document>>,
  'getDashboardStats' : ActorMethod<[], Array<bigint>>,
  'getIndentsByStatus' : ActorMethod<[IndentStatus], Array<Indent>>,
  'getNextCandidateId' : ActorMethod<[], bigint>,
  'getNextIndentId' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateIndentStatus' : ActorMethod<[bigint, IndentStatus, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];