/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const DocumentPhase = IDL.Variant({
  'PreOffer' : IDL.Null,
  'PostOffer' : IDL.Null,
  'PreJoining' : IDL.Null,
});
export const DocumentStatus = IDL.Variant({
  'Uploaded' : IDL.Null,
  'Verified' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const InductionStatus = IDL.Variant({
  'Scheduled' : IDL.Null,
  'Completed' : IDL.Null,
});
export const InterviewStatus = IDL.Variant({
  'Scheduled' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
});
export const OfferStage = IDL.Variant({
  'Sent' : IDL.Null,
  'Draft' : IDL.Null,
  'Rejected' : IDL.Null,
  'Accepted' : IDL.Null,
  'Negotiating' : IDL.Null,
});
export const OnboardingStatus = IDL.Variant({
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ScreeningResult = IDL.Variant({
  'OnHold' : IDL.Null,
  'Rejected' : IDL.Null,
  'Shortlisted' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Source = IDL.Variant({
  'Website' : IDL.Null,
  'Manual' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Opt(IDL.Text),
  'department' : IDL.Opt(IDL.Text),
});
export const Document = IDL.Record({
  'status' : DocumentStatus,
  'blobKey' : IDL.Opt(ExternalBlob),
  'phase' : DocumentPhase,
  'docType' : IDL.Text,
  'candidateId' : IDL.Nat,
});
export const IndentStatus = IDL.Variant({
  'BusinessHeadPending' : IDL.Null,
  'DirectorPending' : IDL.Null,
  'Approved' : IDL.Null,
  'Draft' : IDL.Null,
  'Rejected' : IDL.Null,
});
export const Indent = IDL.Record({
  'id' : IDL.Nat,
  'status' : IndentStatus,
  'jobDescription' : IDL.Text,
  'role' : IDL.Text,
  'experienceRange' : IDL.Text,
  'approver' : IDL.Opt(IDL.Text),
  'createdTimestamp' : Time,
  'department' : IDL.Text,
  'requiredSkills' : IDL.Vec(IDL.Text),
  'positions' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAIInterview' : IDL.Func(
      [IDL.Nat, Time, IDL.Bool, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'addDocument' : IDL.Func(
      [IDL.Nat, DocumentPhase, IDL.Text, DocumentStatus, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'addInduction' : IDL.Func(
      [IDL.Nat, Time, IDL.Vec(IDL.Text), InductionStatus, IDL.Text],
      [],
      [],
    ),
  'addInterviewRound' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        Time,
        InterviewStatus,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addOffer' : IDL.Func([IDL.Nat, IDL.Text, Time, OfferStage], [], []),
  'addOnboardingDay' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, OnboardingStatus, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addScreening' : IDL.Func([IDL.Nat, ScreeningResult, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCandidate' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Text,
        Source,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'createIndent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidateDocuments' : IDL.Func([IDL.Nat], [IDL.Vec(Document)], ['query']),
  'getDashboardStats' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getIndentsByStatus' : IDL.Func([IndentStatus], [IDL.Vec(Indent)], ['query']),
  'getNextCandidateId' : IDL.Func([], [IDL.Nat], []),
  'getNextIndentId' : IDL.Func([], [IDL.Nat], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateIndentStatus' : IDL.Func([IDL.Nat, IndentStatus, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const DocumentPhase = IDL.Variant({
    'PreOffer' : IDL.Null,
    'PostOffer' : IDL.Null,
    'PreJoining' : IDL.Null,
  });
  const DocumentStatus = IDL.Variant({
    'Uploaded' : IDL.Null,
    'Verified' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const InductionStatus = IDL.Variant({
    'Scheduled' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const InterviewStatus = IDL.Variant({
    'Scheduled' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const OfferStage = IDL.Variant({
    'Sent' : IDL.Null,
    'Draft' : IDL.Null,
    'Rejected' : IDL.Null,
    'Accepted' : IDL.Null,
    'Negotiating' : IDL.Null,
  });
  const OnboardingStatus = IDL.Variant({
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ScreeningResult = IDL.Variant({
    'OnHold' : IDL.Null,
    'Rejected' : IDL.Null,
    'Shortlisted' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Source = IDL.Variant({ 'Website' : IDL.Null, 'Manual' : IDL.Null });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Opt(IDL.Text),
    'department' : IDL.Opt(IDL.Text),
  });
  const Document = IDL.Record({
    'status' : DocumentStatus,
    'blobKey' : IDL.Opt(ExternalBlob),
    'phase' : DocumentPhase,
    'docType' : IDL.Text,
    'candidateId' : IDL.Nat,
  });
  const IndentStatus = IDL.Variant({
    'BusinessHeadPending' : IDL.Null,
    'DirectorPending' : IDL.Null,
    'Approved' : IDL.Null,
    'Draft' : IDL.Null,
    'Rejected' : IDL.Null,
  });
  const Indent = IDL.Record({
    'id' : IDL.Nat,
    'status' : IndentStatus,
    'jobDescription' : IDL.Text,
    'role' : IDL.Text,
    'experienceRange' : IDL.Text,
    'approver' : IDL.Opt(IDL.Text),
    'createdTimestamp' : Time,
    'department' : IDL.Text,
    'requiredSkills' : IDL.Vec(IDL.Text),
    'positions' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAIInterview' : IDL.Func(
        [IDL.Nat, Time, IDL.Bool, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'addDocument' : IDL.Func(
        [
          IDL.Nat,
          DocumentPhase,
          IDL.Text,
          DocumentStatus,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'addInduction' : IDL.Func(
        [IDL.Nat, Time, IDL.Vec(IDL.Text), InductionStatus, IDL.Text],
        [],
        [],
      ),
    'addInterviewRound' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          Time,
          InterviewStatus,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addOffer' : IDL.Func([IDL.Nat, IDL.Text, Time, OfferStage], [], []),
    'addOnboardingDay' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, OnboardingStatus, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addScreening' : IDL.Func([IDL.Nat, ScreeningResult, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCandidate' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Text,
          Source,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'createIndent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidateDocuments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getIndentsByStatus' : IDL.Func(
        [IndentStatus],
        [IDL.Vec(Indent)],
        ['query'],
      ),
    'getNextCandidateId' : IDL.Func([], [IDL.Nat], []),
    'getNextIndentId' : IDL.Func([], [IDL.Nat], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateIndentStatus' : IDL.Func([IDL.Nat, IndentStatus, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };