/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Document {
    status: DocumentStatus;
    blobKey?: ExternalBlob;
    phase: DocumentPhase;
    docType: string;
    candidateId: bigint;
}
export interface Indent {
    id: bigint;
    status: IndentStatus;
    jobDescription: string;
    role: string;
    experienceRange: string;
    approver?: string;
    createdTimestamp: Time;
    department: string;
    requiredSkills: Array<string>;
    positions: bigint;
}
export interface UserProfile {
    name: string;
    role?: string;
    department?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum DocumentPhase {
    PreOffer = "PreOffer",
    PostOffer = "PostOffer",
    PreJoining = "PreJoining"
}
export enum DocumentStatus {
    Uploaded = "Uploaded",
    Verified = "Verified",
    Pending = "Pending"
}
export enum IndentStatus {
    BusinessHeadPending = "BusinessHeadPending",
    DirectorPending = "DirectorPending",
    Approved = "Approved",
    Draft = "Draft",
    Rejected = "Rejected"
}
export enum InductionStatus {
    Scheduled = "Scheduled",
    Completed = "Completed"
}
export enum InterviewStatus {
    Scheduled = "Scheduled",
    Cancelled = "Cancelled",
    Completed = "Completed"
}
export enum OfferStage {
    Sent = "Sent",
    Draft = "Draft",
    Rejected = "Rejected",
    Accepted = "Accepted",
    Negotiating = "Negotiating"
}
export enum OnboardingStatus {
    InProgress = "InProgress",
    Completed = "Completed",
    Pending = "Pending"
}
export enum ScreeningResult {
    OnHold = "OnHold",
    Rejected = "Rejected",
    Shortlisted = "Shortlisted"
}
export enum Source {
    Website = "Website",
    Manual = "Manual"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAIInterview(candidateId: bigint, scheduledDate: Time, completed: boolean, score: bigint, summary: string): Promise<void>;
    addDocument(candidateId: bigint, phase: DocumentPhase, docType: string, status: DocumentStatus, blobKey: ExternalBlob | null): Promise<void>;
    addInduction(candidateId: bigint, scheduledDate: Time, topics: Array<string>, status: InductionStatus, notes: string): Promise<void>;
    addInterviewRound(roundNumber: bigint, candidateId: bigint, interviewer: string, scheduledDate: Time, status: InterviewStatus, technical: bigint, communication: bigint, cultural: bigint, overall: bigint, comments: string, recommendation: string): Promise<void>;
    addOffer(candidateId: bigint, ctc: string, joiningDate: Time, stage: OfferStage): Promise<void>;
    addOnboardingDay(dayNumber: bigint, candidateId: bigint, moduleName: string, status: OnboardingStatus, trainer: string, notes: string): Promise<void>;
    addScreening(candidateId: bigint, result: ScreeningResult, notes: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCandidate(name: string, email: string, phone: string, experienceYears: bigint, skills: Array<string>, currentCompany: string, source: Source, indentId: bigint): Promise<bigint>;
    createIndent(department: string, role: string, positions: bigint, jobDescription: string, requiredSkills: Array<string>, experienceRange: string): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCandidateDocuments(candidateId: bigint): Promise<Array<Document>>;
    getDashboardStats(): Promise<Array<bigint>>;
    getIndentsByStatus(status: IndentStatus): Promise<Array<Indent>>;
    getNextCandidateId(): Promise<bigint>;
    getNextIndentId(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateIndentStatus(id: bigint, newStatus: IndentStatus, approver: string): Promise<void>;
}
import type { Document as _Document, DocumentPhase as _DocumentPhase, DocumentStatus as _DocumentStatus, ExternalBlob as _ExternalBlob, Indent as _Indent, IndentStatus as _IndentStatus, InductionStatus as _InductionStatus, InterviewStatus as _InterviewStatus, OfferStage as _OfferStage, OnboardingStatus as _OnboardingStatus, ScreeningResult as _ScreeningResult, Source as _Source, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAIInterview(arg0: bigint, arg1: Time, arg2: boolean, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAIInterview(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAIInterview(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addDocument(arg0: bigint, arg1: DocumentPhase, arg2: string, arg3: DocumentStatus, arg4: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(arg0, to_candid_DocumentPhase_n8(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_DocumentStatus_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(arg0, to_candid_DocumentPhase_n8(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_DocumentStatus_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addInduction(arg0: bigint, arg1: Time, arg2: Array<string>, arg3: InductionStatus, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInduction(arg0, arg1, arg2, to_candid_InductionStatus_n14(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInduction(arg0, arg1, arg2, to_candid_InductionStatus_n14(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async addInterviewRound(arg0: bigint, arg1: bigint, arg2: string, arg3: Time, arg4: InterviewStatus, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: string, arg10: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInterviewRound(arg0, arg1, arg2, arg3, to_candid_InterviewStatus_n16(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInterviewRound(arg0, arg1, arg2, arg3, to_candid_InterviewStatus_n16(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async addOffer(arg0: bigint, arg1: string, arg2: Time, arg3: OfferStage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOffer(arg0, arg1, arg2, to_candid_OfferStage_n18(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOffer(arg0, arg1, arg2, to_candid_OfferStage_n18(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addOnboardingDay(arg0: bigint, arg1: bigint, arg2: string, arg3: OnboardingStatus, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOnboardingDay(arg0, arg1, arg2, to_candid_OnboardingStatus_n20(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOnboardingDay(arg0, arg1, arg2, to_candid_OnboardingStatus_n20(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async addScreening(arg0: bigint, arg1: ScreeningResult, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addScreening(arg0, to_candid_ScreeningResult_n22(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScreening(arg0, to_candid_ScreeningResult_n22(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCandidate(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: Array<string>, arg5: string, arg6: Source, arg7: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCandidate(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Source_n26(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCandidate(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Source_n26(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async createIndent(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: Array<string>, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createIndent(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIndent(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidateDocuments(arg0: bigint): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidateDocuments(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidateDocuments(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getIndentsByStatus(arg0: IndentStatus): Promise<Array<Indent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIndentsByStatus(to_candid_IndentStatus_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIndentsByStatus(to_candid_IndentStatus_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNextCandidateId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextCandidateId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextCandidateId();
            return result;
        }
    }
    async getNextIndentId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextIndentId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextIndentId();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateIndentStatus(arg0: bigint, arg1: IndentStatus, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIndentStatus(arg0, to_candid_IndentStatus_n43(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIndentStatus(arg0, to_candid_IndentStatus_n43(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
}
function from_candid_DocumentPhase_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentPhase): DocumentPhase {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentStatus): DocumentStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_Document_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Promise<Document> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_IndentStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IndentStatus): IndentStatus {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Indent_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Indent): Indent {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: [] | [string];
    department: [] | [string];
}): {
    name: string;
    role?: string;
    department?: string;
} {
    return {
        name: value.name,
        role: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.role)),
        department: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.department))
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _DocumentStatus;
    blobKey: [] | [_ExternalBlob];
    phase: _DocumentPhase;
    docType: string;
    candidateId: bigint;
}): Promise<{
    status: DocumentStatus;
    blobKey?: ExternalBlob;
    phase: DocumentPhase;
    docType: string;
    candidateId: bigint;
}> {
    return {
        status: from_candid_DocumentStatus_n37(_uploadFile, _downloadFile, value.status),
        blobKey: record_opt_to_undefined(await from_candid_opt_n39(_uploadFile, _downloadFile, value.blobKey)),
        phase: from_candid_DocumentPhase_n41(_uploadFile, _downloadFile, value.phase),
        docType: value.docType,
        candidateId: value.candidateId
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _IndentStatus;
    jobDescription: string;
    role: string;
    experienceRange: string;
    approver: [] | [string];
    createdTimestamp: _Time;
    department: string;
    requiredSkills: Array<string>;
    positions: bigint;
}): {
    id: bigint;
    status: IndentStatus;
    jobDescription: string;
    role: string;
    experienceRange: string;
    approver?: string;
    createdTimestamp: Time;
    department: string;
    requiredSkills: Array<string>;
    positions: bigint;
} {
    return {
        id: value.id,
        status: from_candid_IndentStatus_n48(_uploadFile, _downloadFile, value.status),
        jobDescription: value.jobDescription,
        role: value.role,
        experienceRange: value.experienceRange,
        approver: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.approver)),
        createdTimestamp: value.createdTimestamp,
        department: value.department,
        requiredSkills: value.requiredSkills,
        positions: value.positions
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Uploaded: null;
} | {
    Verified: null;
} | {
    Pending: null;
}): DocumentStatus {
    return "Uploaded" in value ? DocumentStatus.Uploaded : "Verified" in value ? DocumentStatus.Verified : "Pending" in value ? DocumentStatus.Pending : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PreOffer: null;
} | {
    PostOffer: null;
} | {
    PreJoining: null;
}): DocumentPhase {
    return "PreOffer" in value ? DocumentPhase.PreOffer : "PostOffer" in value ? DocumentPhase.PostOffer : "PreJoining" in value ? DocumentPhase.PreJoining : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BusinessHeadPending: null;
} | {
    DirectorPending: null;
} | {
    Approved: null;
} | {
    Draft: null;
} | {
    Rejected: null;
}): IndentStatus {
    return "BusinessHeadPending" in value ? IndentStatus.BusinessHeadPending : "DirectorPending" in value ? IndentStatus.DirectorPending : "Approved" in value ? IndentStatus.Approved : "Draft" in value ? IndentStatus.Draft : "Rejected" in value ? IndentStatus.Rejected : value;
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Promise<Array<Document>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Document_n35(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Indent>): Array<Indent> {
    return value.map((x)=>from_candid_Indent_n46(_uploadFile, _downloadFile, x));
}
function to_candid_DocumentPhase_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentPhase): _DocumentPhase {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentStatus): _DocumentStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_IndentStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IndentStatus): _IndentStatus {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_InductionStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InductionStatus): _InductionStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_InterviewStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterviewStatus): _InterviewStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_OfferStage_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OfferStage): _OfferStage {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_OnboardingStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OnboardingStatus): _OnboardingStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_ScreeningResult_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScreeningResult): _ScreeningResult {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_Source_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Source): _Source {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role?: string;
    department?: string;
}): {
    name: string;
    role: [] | [string];
    department: [] | [string];
} {
    return {
        name: value.name,
        role: value.role ? candid_some(value.role) : candid_none(),
        department: value.department ? candid_some(value.department) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentStatus): {
    Uploaded: null;
} | {
    Verified: null;
} | {
    Pending: null;
} {
    return value == DocumentStatus.Uploaded ? {
        Uploaded: null
    } : value == DocumentStatus.Verified ? {
        Verified: null
    } : value == DocumentStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InductionStatus): {
    Scheduled: null;
} | {
    Completed: null;
} {
    return value == InductionStatus.Scheduled ? {
        Scheduled: null
    } : value == InductionStatus.Completed ? {
        Completed: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterviewStatus): {
    Scheduled: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
} {
    return value == InterviewStatus.Scheduled ? {
        Scheduled: null
    } : value == InterviewStatus.Cancelled ? {
        Cancelled: null
    } : value == InterviewStatus.Completed ? {
        Completed: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OfferStage): {
    Sent: null;
} | {
    Draft: null;
} | {
    Rejected: null;
} | {
    Accepted: null;
} | {
    Negotiating: null;
} {
    return value == OfferStage.Sent ? {
        Sent: null
    } : value == OfferStage.Draft ? {
        Draft: null
    } : value == OfferStage.Rejected ? {
        Rejected: null
    } : value == OfferStage.Accepted ? {
        Accepted: null
    } : value == OfferStage.Negotiating ? {
        Negotiating: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OnboardingStatus): {
    InProgress: null;
} | {
    Completed: null;
} | {
    Pending: null;
} {
    return value == OnboardingStatus.InProgress ? {
        InProgress: null
    } : value == OnboardingStatus.Completed ? {
        Completed: null
    } : value == OnboardingStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScreeningResult): {
    OnHold: null;
} | {
    Rejected: null;
} | {
    Shortlisted: null;
} {
    return value == ScreeningResult.OnHold ? {
        OnHold: null
    } : value == ScreeningResult.Rejected ? {
        Rejected: null
    } : value == ScreeningResult.Shortlisted ? {
        Shortlisted: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Source): {
    Website: null;
} | {
    Manual: null;
} {
    return value == Source.Website ? {
        Website: null
    } : value == Source.Manual ? {
        Manual: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IndentStatus): {
    BusinessHeadPending: null;
} | {
    DirectorPending: null;
} | {
    Approved: null;
} | {
    Draft: null;
} | {
    Rejected: null;
} {
    return value == IndentStatus.BusinessHeadPending ? {
        BusinessHeadPending: null
    } : value == IndentStatus.DirectorPending ? {
        DirectorPending: null
    } : value == IndentStatus.Approved ? {
        Approved: null
    } : value == IndentStatus.Draft ? {
        Draft: null
    } : value == IndentStatus.Rejected ? {
        Rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentPhase): {
    PreOffer: null;
} | {
    PostOffer: null;
} | {
    PreJoining: null;
} {
    return value == DocumentPhase.PreOffer ? {
        PreOffer: null
    } : value == DocumentPhase.PostOffer ? {
        PostOffer: null
    } : value == DocumentPhase.PreJoining ? {
        PreJoining: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
